apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bear
    group: animals
  name: green
spec:
  selector:
    matchLabels:
      group: animals
      app: bear
  replicas: 1
  template:
    metadata:
      labels:
        group: animals
        app: bear
    spec:
      containers:
      - name: bear
        image: supergiantkir/animals:bear
        ports:
        - containerPort: 80
